apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-a4dk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-a4dk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0041-app
  name: devfile-sample-a4dk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-a4dk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-a4dk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0041-tenant/tkrw-pr712-0075-0041-app/devfile-sample-a4dk@sha256:abff5c1f26f3b3b0a770caa01c6451ea51f287833b4713f040eb757764a08a95
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
